"use client";

import type { SavedRun } from "@/lib/tf/types";
import { buttonStyle, pct, rightPanelTitleStyle } from "@/components/playground/ui";

export function CompareExperiments({ savedRuns, onSaveRun, onRemoveRun }: { savedRuns: SavedRun[]; onSaveRun: () => void; onRemoveRun: (id: string) => void }) {
  return <div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}><p style={rightPanelTitleStyle}>Compare experiments</p><button onClick={onSaveRun} style={{ ...buttonStyle(true), height: 32, minWidth: 72 }}>save run</button></div><div style={{ display: "grid", gap: 8 }}>{savedRuns.length === 0 && <p style={{ color: "#52525b", fontSize: 11 }}>Save two runs to compare architectures and generalization.</p>}{savedRuns.map((run) => <div key={run.id} style={{ border: "1px solid #1e1e22", borderRadius: 10, background: "rgba(255,255,255,0.018)", padding: 11 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><b style={{ fontSize: 11, color: "#e4e4e7" }}>{run.name}</b><button onClick={() => onRemoveRun(run.id)} style={{ background: "none", border: 0, color: "#52525b", cursor: "pointer" }}>×</button></div><p style={{ marginTop: 5, fontSize: 9, color: "#52525b" }}>{run.datasetName} · {run.layers.map((l) => l.neurons).join("→")}</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 8, marginTop: 10 }}><Metric k="test" v={pct(run.metrics?.testAccuracy ?? 0)} /><Metric k="gap" v={pct(run.metrics?.generalizationGap ?? 0)} /><Metric k="loss" v={run.loss === null ? "—" : run.loss.toFixed(3)} /></div><div style={{ marginTop: 9, height: 4, borderRadius: 999, background: "#17171b", overflow: "hidden" }}><div style={{ width: `${Math.round((run.metrics?.testAccuracy ?? 0) * 100)}%`, height: "100%", background: "linear-gradient(90deg,#7c3aed,#ec4899)" }} /></div></div>)}</div></div>;
}
function Metric({ k, v }: { k: string; v: string }) { return <div><div style={{ fontSize: 8, color: "#444", textTransform: "uppercase", letterSpacing: "0.12em" }}>{k}</div><div style={{ marginTop: 3, fontSize: 11, color: "#a1a1aa", fontFamily: "'JetBrains Mono', monospace" }}>{v}</div></div>; }
